environment: local
namespace: core-dev
image:
  tag: latest # set to your local image tag if needed

# settings for ingest
discoveryservice:
  kafka:
    bootstrapServers: "kafka.core-dev:9092"
    timeout: 2
    consumer:
      errorTopic: "ubirch-svalbard-evt-relation-json-error"
      topics: "ubirch-svalbard-evt-relation-json"
      group: "discovery-kafka"
      poolRecords: 500
    producer:
      topics: "ubirch-svalbard-evt-relation-json"
      errorTopic: "ubirch-svalbard-evt-relation-json-error"
    gremlinConf:
      asynchronousBatchSize: 8
  prometheus:
    port: 4321
    namespace: "ubirch_discovery_service"
  core:
    hosts: "janusgraph.core-dev"
    port: 8182
    connectionPool:
      reconnectInterval: 500
      maxWaitForConnection: 6000

prometheus:
  namespace: prometheus-dev