apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "thischart.name" .}}
  namespace: prometheus
  labels:
    app: {{ template "thischart.name" .}}
    release: prometheus-operator
spec:
  endpoints:
    - interval: 30s
      path: /
      port: prometheus-metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    name: {{ template "thischart.name" .}}
