version: '3'
services:
  janus:
    image: jg-no-es:jg
    networks:
      our_network:
        ipv4_address: 172.28.1.2
    ports:
      - "8182:8182"
    depends_on:
      - db
  db:
    image: cassandra:3.11
    networks:
      our_network:
        ipv4_address: 172.28.1.5
    ports:
      - "9160:9160"
      - "9042:9042"
      - "7199:7199"
      - "7001:7001"
      - "7000:7000"
    environment:
      - CASSANDRA_START_RPC=true
networks:
  our_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

